services:

  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    depends_on:
      - app
      - db

  app:
    build: ./docker/php
    volumes:
      - ./:/var/www/
    depends_on:
      - db

  db:
    image: mysql:latest
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports: 
      - "3306:3306"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=students
  
  phpmyadmin2:
    image: phpmyadmin
    ports:
      - 1500:80
    environment:
      - PMA_HOST=db
    depends_on:
      - db